# Generated by Django 4.2.7 on 2026-09-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_warehouses_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='designname',
            name='price_per_meter',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
