# Generated by Django 4.2.7 on 2026-09-25 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('design_number', models.CharField(max_length=30)),
                ('move_type', models.CharField(max_length=20)),
                ('requested_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.inventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reserved_inventory',
            },
        ),
    ]
